### ISSUE TITLE
DevTools problem

### ISSUE THREAD

**Issue by TinMan5** [jjjchens235/bing-rewards#111]
> Starting Edge search

DevTools listening on ws://127.0.0.1:59246/devtools/browser/be15caf7-83b6-4a1b-8159-131b120dd1fd
Traceback (most recent call last):
  File "BingRewards/BingRewards.py", line 164, in <module>
    __main()
  File "BingRewards/BingRewards.py", line 76, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "C:\Users\jaypl\AppData\Local\Programs\Python\Python36\BingRewards\src\rewards.py", line 1266, in complete_all
    driver = self.__complete_edge_search()
  File "C:\Users\jaypl\AppData\Local\Programs\Python\Python36\BingRewards\src\rewards.py", line 1065, in __complete_edge_search
    self.path, Driver.WEB_DEVICE, self.headless, self.cookies
  File "C:\Users\jaypl\AppData\Local\Programs\Python\Python36\BingRewards\src\driver.py", line 135, in get_driver
    driver = webdriver.Chrome(path, options=options)
  File "C:\Users\jaypl\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\jaypl\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\jaypl\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\jaypl\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\jaypl\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist

**Comment by jasperan** [comment]
Having the same issue from the last update

**Comment by jjjchens235** [comment]
Can you guys try two things for me as I cannot reproduce this bug myself.
Under this [line of code](https://github.com/jjjchens235/bing-rewards/blob/6322b7d0623ee3a2bb5d7844362965b5fc75f059/BingRewards/src/driver.py#L112) first try adding:

`options.add_argument('--remote-debugging-port=9222')`

Now, re-run it.

If that doesn't work, **replace** the above line of code with the following 
``` py
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
```

Let me know if either of those solutions works. In the meantime I'll try to figure out if I can add some exception handling over the next few days.

**Comment by jasperan** [comment]
hi @jjjchens235, here are some logs:

```
E:\Programs\github\bing-rewards (HEAD detached at d978a6c)
λ git branch -a
* (HEAD detached at d978a6c)
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/dev
  remotes/origin/master

E:\Programs\github\bing-rewards (HEAD detached at d978a6c)
λ git checkout remotes/origin/dev
Previous HEAD position was d978a6c added AUS to country list
HEAD is now at 05801a7 cookie error handling

E:\Programs\github\bing-rewards (HEAD detached at 05801a7)
λ ls
BingRewards/  LICENSE  README.md  setup.py

E:\Programs\github\bing-rewards (HEAD detached at 05801a7)
λ pyt

E:\Programs\github\bing-rewards (HEAD detached at 05801a7)
λ cd BingRewards\

E:\Programs\github\bing-rewards\BingRewards (HEAD detached at 05801a7)
λ python BingRewards.py

Command line options selected:
search_type=remaining, headless=True, email=None

['Wed, Nov 17 2021 11:21PM', 'Failed Offers']

        You selected remaining

> Starting offers

DevTools listening on ws://127.0.0.1:9222/devtools/browser/2ebc1a2c-3579-4ae9-a419-746e7d9c749d
       >> Logging in
[1118/015954.140:ERROR:disk_cache.cc(184)] Unable to create cache
           << Successfully logged in
```

The print you said doesn't appear in screen as far as I can see.

**Comment by jasperan** [comment]
Also, I may have found an additional error in this version at the end of execution (dev branch as well):

```
Traceback (most recent call last):
  File "BingRewards.py", line 164, in <module>
    __main()
  File "BingRewards.py", line 84, in __main
    rewards.complete_offers()
  File "E:\Programs\github\bing-rewards\BingRewards\src\rewards.py", line 1252, in complete_offers
    driver = self.__complete_offers()
  File "E:\Programs\github\bing-rewards\BingRewards\src\rewards.py", line 1154, in __complete_offers
    self.completion.offers = self.__offers(driver)
  File "E:\Programs\github\bing-rewards\BingRewards\src\rewards.py", line 1047, in __offers
    c = self.__click_offer(
  File "E:\Programs\github\bing-rewards\BingRewards\src\rewards.py", line 958, in __click_offer
    completed = self.__quiz2(driver)
  File "E:\Programs\github\bing-rewards\BingRewards\src\rewards.py", line 798, in __quiz2
    for x in re.match("\((\d+) of (\d+)\)", progress).groups()
AttributeError: 'NoneType' object has no attribute 'groups'

```

**Comment by wastingoctober** [comment]
My dev branch reports the following, but it does successfully complete now!

```
DevTools listening on ws://127.0.0.1:9222/devtools/browser/d146f9b0-8c59-40c5-8236-2d3f446924c7
       >> Logging in
[1119/093848.866:ERROR:database.cc(1773)] Cookie SQLite error: code 14 errno -2: unable to open database file sql: -- sqlite3_open()
[1119/093848.866:ERROR:database.cc(1773)] Cookie SQLite error: code 14 errno -2: unable to open database file sql: -- sqlite3_open()
[1119/093848.867:ERROR:disk_cache.cc(185)] Unable to create cache
```

**Comment by jasperan** [comment]
@wastingoctober it will stay for you locally at least until you pull from the repository again

**Comment by jjjchens235** [comment]
@jasperan @wastingoctober  Thanks for taking a look!
It seems that adding that adding this line of code to driver.py
```py
#option 1
options.add_argument('--remote-debugging-port=9222')
```
allows the program to continue without erroring out, but it doesn't allow the cookies to be saved still per the log message `Unable to create cache`.

Meaning if you got the `DevTools error` originally, cookies won't be saved regardless.
Since that's the case, I'm considering removing the line above, and instead, when the original error is thrown, handle the error by creating a driver object with the original logic without cookies.

This would result in people without DevTool error being able to use chromedriver with cookies, and those with the error using the original chromedriver.

What do you guys think and would you guys mind testing this if I updated dev branch?

**Comment by jjjchens235** [comment]
> My dev branch reports the following, but it does successfully complete now!
> 
> ```
> DevTools listening on ws://127.0.0.1:9222/devtools/browser/d146f9b0-8c59-40c5-8236-2d3f446924c7
>        >> Logging in
> [1119/093848.866:ERROR:database.cc(1773)] Cookie SQLite error: code 14 errno -2: unable to open database file sql: -- sqlite3_open()
> [1119/093848.866:ERROR:database.cc(1773)] Cookie SQLite error: code 14 errno -2: unable to open database file sql: -- sqlite3_open()
> [1119/093848.867:ERROR:disk_cache.cc(185)] Unable to create cache
> ```
> 
> out of curiosity, what will happen when this dev branch gets closed? do we have to switch our branches back to master, or will it automatically do that? I don't use git all that heavily.

The dev branch will never be closed, so you can continue to use it as long as you like. I would advise you to switch back to master once I have closed this issue- that would signal that I have merged the changes in dev back to master.

The reason to switch back to master is b/c generally dev is more of an experimental branch, so if you pull in new changes, it may break the program. Ironically in this case, this 'experimental' branch seems to be working more than 'master'- this is generally not the case.

**Comment by wastingoctober** [comment]
> @jasperan @wastingoctober Thanks for taking a look! It seems that adding that adding this line of code to driver.py
> 
> ```python
> #option 1
> options.add_argument('--remote-debugging-port=9222')
> ```
> 
> allows the program to continue without erroring out, but it doesn't allow the cookies to be saved still per the log message `Unable to create cache`.
> 
> Meaning if you got the `DevTools error` originally, cookies won't be saved regardless. Since that's the case, I'm considering removing the line above, and instead, when the original error is thrown, handle the error by creating a driver object with the original logic without cookies.
> 
> This would result in people without DevTool error being able to use chromedriver with cookies, and those with the error using the original chromedriver.
> 
> What do you guys think and would you guys mind testing this if I updated dev branch?

sure, I appreciate the dedication to the project! I actually run my script multiple times per day and always pull the latest changes before running. I’m still on the dev branch.

**Comment by jjjchens235** [comment]
Cool, I have updated `dev` branch,  please let me know if this fixes the issues

**Comment by wastingoctober** [comment]
> Cool, I have updated `dev` branch, please let me know if this fixes the issues

I received no errors running the script this time! I didn’t have any tasks left to run on any of my accounts though, so I can’t verify beyond the fact that I got no errors.

**Comment by jasperan** [comment]
@jjjchens235 @wastingoctober this is the result of my tests in the new update:

λ python BingRewards\BingRewards.py -nhl                                                              
                                                                                                      
Command line options selected:                                                                        
search_type=remaining, headless=False, email=None                                                     
                                                                                                      
['Sat, Nov 20 2021 07:23PM', 'Failed Mobile Search, Offers']                                          
                                                                                                      
        You selected remaining                                                                        
                                                                                                      
> Starting offers                                                                                     
Trying chromedriver without cookies option                                                            
                                                                                                      
```
DevTools listening on ws://127.0.0.1:55414/devtools/browser/5d5ae9ec-8d92-4146-9912-1a60f7c82d2c      
       >> Logging in                                                                                  
           << Successfully logged in                                                                  
       >> Trying Que empiece el juego!                                                                
           << Already checked                                                                         
       >> Trying Qu sabes de superhroes?                                                              
           << Already checked                                                                         
       >> Trying Compras                                                                              
              >>> Checking cookies popup                                                              
              >>> No cookie popup present                                                             
              >>> Starting quiz                                                                       
                  <<< Could not detect quiz overlay                                                   
              >>> Starting quiz2 (no overlay)                                                         
              >>> Could not find quiz2 progress elements                                              
           << Failed to complete Compras                                                              
       >> Trying Oh, menudos paisajes!                                                                
              >>> skipping quiz - assuming it offers no points                                        
       >> Trying Quiz de noticias                                                                     
              >>> Starting quiz                                                                       
                  <<< Could not detect quiz overlay                                                   
              >>> Starting quiz2 (no overlay)                                                         
Traceback (most recent call last):                                                                    
  File "BingRewards\BingRewards.py", line 164, in <module>                                            
    __main()                                                                                          
  File "BingRewards\BingRewards.py", line 84, in __main                                               
    rewards.complete_offers()                                                                         
  File "E:\Programs\github\bing-rewards\BingRewards\src\rewards.py", line 1252, in complete_offers    
    driver = self.__complete_offers()                                                                 
  File "E:\Programs\github\bing-rewards\BingRewards\src\rewards.py", line 1154, in __complete_offers  
    self.completion.offers = self.__offers(driver)                                                    
  File "E:\Programs\github\bing-rewards\BingRewards\src\rewards.py", line 1047, in __offers           
    c = self.__click_offer(                                                                           
  File "E:\Programs\github\bing-rewards\BingRewards\src\rewards.py", line 958, in __click_offer       
    completed = self.__quiz2(driver)                                                                  
  File "E:\Programs\github\bing-rewards\BingRewards\src\rewards.py", line 798, in __quiz2             
    for x in re.match("\((\d+) of (\d+)\)", progress).groups()                                        
AttributeError: 'NoneType' object has no attribute 'groups'                                           
```

**Comment by jjjchens235** [comment]
@jasperan i suspect if you check out to a previous hash before cookies were introduced, you would still run into this error, the previous hash starts with `86f4a4f`

**Comment by jjjchens235** [comment]
I had to update `dev` branch per error that David reported above.
Once I get or or two people to confirm that dev branch works properly, I'll merge to master and this should fix the issue.

**Comment by wastingoctober** [comment]
> I had to update `dev` branch per error that David reported above. Once I get or or two people to confirm that dev branch works properly, I'll merge to master and this should fix the issue.

I am seeing the following errors:

`Command line options selected:
search_type=remaining, headless=True, email=None

['Mon, Nov 22 2021 07:11AM', 'Failed Edge Search, Web Search, Mobile Search, Offers']

        You selected remaining

> Starting Edge search

DevTools listening on ws://127.0.0.1:63896/devtools/browser/162b8d9c-ce29-4dcd-9862-3e3077102c43
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Code\bing-rewards-user\bing-rewards\BingRewards\src\driver.py", line 147, in get_driver
    driver = webdriver.Chrome(path, options=options)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\BingRewards\BingRewards.py", line 164, in <module>
    __main()
  File ".\BingRewards\BingRewards.py", line 76, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "C:\Users\user\OneDrive\Code\bing-rewards-user\bing-rewards\BingRewards\src\rewards.py", line 1266, in complete_all
    driver = self.__complete_edge_search()
  File "C:\Users\user\OneDrive\Code\bing-rewards-user\bing-rewards\BingRewards\src\rewards.py", line 1065, in __complete_edge_search
    self.path, Driver.WEB_DEVICE, self.headless, self.cookies
  File "C:\Users\user\OneDrive\Code\bing-rewards-user\bing-rewards\BingRewards\src\driver.py", line 159, in get_driver
    if "DevToolsActivePort file doesn't exist" in wde.value:
AttributeError: 'WebDriverException' object has no attribute 'value'`

**Comment by jjjchens235** [comment]
updated, can you try again plz

**Comment by wastingoctober** [comment]
> updated, can you try again plz

looks like that fixed it for me! I got an exception technically completing all my extra tasks, but they're all completed. so they must have just been phantom ones or ones that were already done.

**Comment by wastingoctober** [comment]
correction: I spoke too soon. I got a report that mobile search failed at 45/100 as well. re-running it was successful though.

I am still seeing this error between the desktop and mobile sections, but it doesn't appear to be causing any problems. 

```
> Starting mobile search

DevTools listening on ws://127.0.0.1:63040/devtools/browser/30b747c9-37cf-41e9-a1e2-2c949de31a7b

webdriverexception msg: Message: unknown error: DevToolsActivePort file doesn't exist

Trying chromedriver without cookies option
```

**Comment by jjjchens235** [comment]
Thanks for re-running, I have merged to master.


The mobile not completing is a different issue, I encountered close to a month ago, and I'm not sure if it's a driver issue or a bing issue, what is happening is that the google trends search string is not being entered in the search bar for some reason.

**Comment by wastingoctober** [comment]
@jjjchens235 thank you so much for the hard work here!
