### ISSUE TITLE
Fail Desktop search + fail mobile search

### ISSUE THREAD

**Issue by heximing** [jjjchens235/bing-rewards#263]
![20220829081945](https://user-images.githubusercontent.com/541861/187199796-d2821465-a18e-4651-9543-ac5848832ea5.jpg)
It does not have error/exceptions. Just cannot earn points.

**Comment by pearlheartgtr** [comment]
Same here. Since the last update, I've also had to run the program at least 3-4 times to finish everything.

**Comment by DimaRazb** [comment]
Same. So prob MS broke something again :(

**Comment by RotatingWires** [comment]
Same issues.

**Comment by jjjchens235** [comment]
This should be fixed, changes in master, bf5d19e

**Comment by erichobson** [comment]
I keep running into this issues on all of my devices. I've tried on multiple devices and tried updating. Not sure if I am doing something wrong as everything has worked before yesterday.

> Starting Mobile search
       >> Starting search
              >>> Progress: [##################            ] 36/60 (60%)Traceback (most recent call last):
  File "C:\Users\Eric\Documents\GitHub\bing-rewards\BingRewards\BingRewards.py", line 179, in <module>
    main()
  File "C:\Users\Eric\Documents\GitHub\bing-rewards\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\Eric\Documents\GitHub\bing-rewards\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\Eric\Documents\GitHub\bing-rewards\BingRewards\src\rewards.py", line 1384, in complete_search_type
    self.complete_remaining_searches(search_type, prev_completion)
  File "C:\Users\Eric\Documents\GitHub\bing-rewards\BingRewards\src\rewards.py", line 1364, in complete_remaining_searches
    self.__complete_mobile_search()
  File "C:\Users\Eric\Documents\GitHub\bing-rewards\BingRewards\src\rewards.py", line 1330, in __complete_mobile_search
    self.completion.mobile_search = self.__complete_action(
  File "C:\Users\Eric\Documents\GitHub\bing-rewards\BingRewards\src\rewards.py", line 1288, in __complete_action
    completion = action(**action_kwargs)
  File "C:\Users\Eric\Documents\GitHub\bing-rewards\BingRewards\src\rewards.py", line 377, in __search
    search_box.send_keys(query, Keys.RETURN)  # unique search term
  File "C:\Users\Eric\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 255, in send_keys
    self._dispatch("change_value_of", (self._webelement, self._driver), "send_keys", value)
  File "C:\Users\Eric\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 330, in _dispatch
    result = getattr(self._webelement, d_call)(*d_args)
  File "C:\Users\Eric\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 600, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\Eric\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 773, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Eric\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Eric\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=)
Stacktrace:
Backtrace:
        Ordinal0 [0x011B78B3+2193587]
        Ordinal0 [0x01150681+1771137]
        Ordinal0 [0x010641A8+803240]
        Ordinal0 [0x01066BB4+814004]
        Ordinal0 [0x01066A72+813682]
        Ordinal0 [0x01066D00+814336]
        Ordinal0 [0x01092FA6+995238]
        Ordinal0 [0x01093081+995457]
        Ordinal0 [0x0108B8B9+964793]
        Ordinal0 [0x010AD7AC+1103788]
        Ordinal0 [0x01088C04+953348]
        Ordinal0 [0x010AD9C4+1104324]
        Ordinal0 [0x010BDAE2+1170146]
        Ordinal0 [0x010AD5C6+1103302]
        Ordinal0 [0x010877E0+948192]
        Ordinal0 [0x010886E6+952038]
        GetHandleVerifier [0x01460CB2+2738370]
        GetHandleVerifier [0x014521B8+2678216]
        GetHandleVerifier [0x012417AA+512954]
        GetHandleVerifier [0x01240856+509030]
        Ordinal0 [0x0115743B+1799227]
        Ordinal0 [0x0115BB68+1817448]
        Ordinal0 [0x0115BC55+1817685]
        Ordinal0 [0x01165230+1856048]
        BaseThreadInitThunk [0x768A6739+25]
        RtlGetFullPathName_UEx [0x773590AF+1215]
        RtlGetFullPathName_UEx [0x7735907D+1165]

**Comment by jjjchens235** [comment]
run it with `-nhl` what is actually happening? what page is it erorring out on?

**Comment by erichobson** [comment]
It ran through about 3 searches normally and then just closed.

**Comment by RotatingWires** [comment]
> This should be fixed, changes in master, [bf5d19e](https://github.com/jjjchens235/bing-rewards/commit/bf5d19eabc5a0b6e359522cd905ad4992f8ec71a)

![image](https://user-images.githubusercontent.com/100501698/187307538-252edeb6-aca0-4a7f-baf6-a827a3a27030.png)

still getting this issue

**Comment by pearlheartgtr** [comment]
Same as above. Won't complete Mobile search.

**Comment by eriph** [comment]
Mobile search started working for me when I changed mobile user agent to beta chrome driver 105.0.5195.19

**Comment by pearlheartgtr** [comment]
> Mobile search started working for me when I changed mobile user agent to beta chrome driver 105.0.5195.19

How?

**Comment by BCusack** [comment]
seems to crash out at line 379 rewards.py -> made it through while in debug with a break point at ```time.sleep(random.uniform(2, 4.5))```
Will test beta chrome driver 105.0.5195.19 and increasing the delay tomorrow. Let you know.

**Comment by kolatez** [comment]
all 3 searches appear to be broken

**Comment by heximing** [comment]
> all 3 searches appear to be broken

Same.

**Comment by buzzbros2002** [comment]
Adding -NSB seems to get through everything BUT the failed mobile search, at least that's what I've seen as a workaround from the following that I saw closed in the changelog:

https://github.com/jjjchens235/bing-rewards/issues/252

Mobile search still needs fixing.

> BCusack:
>  Will test beta chrome driver 105.0.5195.19 and increasing the delay tomorrow. Let you know.

Hopefully this brings some results. Fingers crossed.

**Comment by BCusack** [comment]
No good 
![image](https://user-images.githubusercontent.com/10039059/187598656-0433a857-afbc-4267-8a0d-1294466f654e.png)

**Comment by BCusack** [comment]
Added a sleep before search_box and all completed. I've had issues with "visibility_of_element_located" before, will try "presence_of_element_located" for tomorrow.

**Comment by marcodallagatta** [comment]
Same here, this is what I get:
```
C:\Users\User\Documents>python C:\Users\User\Documents\github\bing-rewards\BingRewards\BingRewards.py -d msedge -nhl -r

Command line options selected:
email=None, search_type=remaining, driver=<class 'src.driver.MsEdgeDriverFactory'>, headless=False, cookies=False, nosandbox=False, telegram=False, discord=False, google_sheets=False, google_trends_geo=US

['Wed, Aug 31 2022 02:50PM', 'Failed Offers, Latest Punch Card Activity']

You selected remaining

DevTools listening on ws://127.0.0.1:5637/devtools/browser/b5f5a951-8614-442d-b55c-4d13725ad2fc
       >> Logging in
           << Successfully logged in
> Starting Offers
       >> Trying Lubrificati con questo quiz
              >>> Checking cookies popup
              >>> cookie popup cleared
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
                     >>>> Progress: [##############################] 5/5 (100%)
                  <<< Successfully completed quiz2
           << Successfully completed 'Lubrificati con questo quiz'
Traceback (most recent call last):
  File "C:\Users\User\Documents\github\bing-rewards\BingRewards\BingRewards.py", line 179, in <module>
    main()
  File "C:\Users\User\Documents\github\bing-rewards\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\User\Documents\github\bing-rewards\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\User\Documents\github\bing-rewards\BingRewards\src\rewards.py", line 1384, in complete_search_type
    self.complete_remaining_searches(search_type, prev_completion)
  File "C:\Users\User\Documents\github\bing-rewards\BingRewards\src\rewards.py", line 1368, in complete_remaining_searches
    self.__complete_offers()
  File "C:\Users\User\Documents\github\bing-rewards\BingRewards\src\rewards.py", line 1338, in __complete_offers
    self.completion.offers = self.__complete_action(
  File "C:\Users\User\Documents\github\bing-rewards\BingRewards\src\rewards.py", line 1288, in __complete_action
    completion = action(**action_kwargs)
  File "C:\Users\User\Documents\github\bing-rewards\BingRewards\src\rewards.py", line 1115, in __offers
    self.__perform_action_on_offers(self.__click_offer, daily_sets_xpath, [], offer_count=3)
  File "C:\Users\User\Documents\github\bing-rewards\BingRewards\src\rewards.py", line 1089, in __perform_action_on_offers
    self.driver.close_other_tabs()
  File "C:\Users\User\Documents\github\bing-rewards\BingRewards\src\driver.py", line 35, in close_other_tabs
    self.close()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 102, in close
    self._dispatch("close", (self._driver,), "close", ())
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 180, in _dispatch
    result = getattr(self._driver, d_call)(*d_args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 943, in close
    self.execute(Command.CLOSE)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unexpected command response
  (Session info: MicrosoftEdge=104.0.1293.70)
Stacktrace:
Backtrace:
        Microsoft::Applications::Events::EventProperties::unpack [0x00007FF661556292+24642]
        Microsoft::Applications::Events::GUID_t::GUID_t [0x00007FF6614A99E2+334098]
        Ordinal0 [0x00007FF661047915+620821]
        Ordinal0 [0x00007FF6610364C5+550085]
        Ordinal0 [0x00007FF661035A7B+547451]
        Ordinal0 [0x00007FF661034E45+544325]
        Ordinal0 [0x00007FF661034553+542035]
        Ordinal0 [0x00007FF6610343C0+541632]
        Ordinal0 [0x00007FF661048CB1+625841]
        Ordinal0 [0x00007FF6610A6CB2+1010866]
        Ordinal0 [0x00007FF66109EE60+978528]
        Ordinal0 [0x00007FF661075F00+810752]
        Ordinal0 [0x00007FF661077508+816392]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF66130D478+135480]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6612F4B77+34871]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6612F7BFC+47292]
        Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6611511B6+23222]
        Microsoft::Applications::Events::GUID_t::GUID_t [0x00007FF6614B0EEB+364059]
        Microsoft::Applications::Events::GUID_t::GUID_t [0x00007FF6614B5924+383060]
        Microsoft::Applications::Events::GUID_t::GUID_t [0x00007FF6614B5A7D+383405]
        Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x00007FF6614C038E+39918]
        BaseThreadInitThunk [0x00007FFC8A4854E0+16]
        RtlUserThreadStart [0x00007FFC8B48485B+43]


[process exited with code 1 (0x00000001)]
```

**Comment by SouthBaySoftware** [comment]
> Mobile search started working for me when I changed mobile user agent to beta chrome driver 105.0.5195.19

This worked for me also. I was failing only mobile searches, which did not complete fully.
This fix does not involve switching to the beta chrome driver, merely changing the chrome user agent in the driver.py file on line 55 to read; 

`__MOBILE_USER_AGENT = "Mozilla/5.0 (Linux; Android 10; HD1913) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.5195.19 Mobile Safari/537.36 EdgA/100.0.1185.50"`

**Comment by heximing** [comment]
change driver.py Line 54~55 to below fix BOTH web search and mobile search for me. You guys can try.

`    __WEB_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/104.0.1293.70"
    __MOBILE_USER_AGENT = "Mozilla/5.0 (Linux; Android 10; HD1913) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.5195.19 Mobile Safari/537.36 EdgA/100.0.1185.50"`

**Comment by DimaRazb** [comment]
@heximing , your trick fixed this for my US market but the Canadian web search keeps failing. Looks like MS changed something.

**Comment by connect-dots** [comment]
I'm in the same boat as @DimaRazb on this one - the fix isnt working in the UK either  - all three searches are bombing out.

**Comment by fexofenadine** [comment]
mine inexplicably started working again for me last nigh, and again this morning. the only explanation o can think of is chrome updated itself or ms changed something in their api

**Comment by jjjchens235** [comment]
Closing this out as I think any remaining issues were resolved by the chrome update to v105
